# General settings
title: A programmer's pondering
email: alex_schouls@live.com
description: >-
  A blog about software engineering and architecture.
domain: physer.github.io
baseurl: ""
url: ""
github_username: physer

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Umami settings
umami_tracking_id: e661d103-0c86-4a79-b1cf-7b1e4a530a97
