# General settings
title: A programmer's pondering
email: alex_schouls@live.com
description: >-
  A blog about software engineering and architecture.
domain: physer.github.io
baseurl: ""
url: ""
github_username:  physer

# Build settings
theme: minima
plugins:
  - jekyll-feed
